services:
  front:
    image: docker-frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"

  server:
    image: docker-backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
  